### ISSUE TITLE
V3.0.0 not working

### ISSUE THREAD

**Issue by sergiopera** [momocow/OGame-Redesign-v.6-Auction-Timer#5]
Hello this version completely stopped working, is that correct?

**Comment by momocow** [comment]
Yes, because it is not ready yet.
`AuctionTimer.js` is the currently stable one.

`AuctionTimer.user.js` is for v3.0.0.
I'm also preparing a guide for you to set up the auto-update flow.
You should currently copy and paste the content of the script to install it,
but you won't have to do that after v3.0.0 released, Tampermonkey will do that for you.
